add_friend/urls.py
from django.conf.urls import url
from .views import index,add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
]

profile_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

socmedProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import profile_page.urls as profile_page
import update_status.urls as update_status
import statistic.urls as statistic
import add_friend.urls as friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile-page/', include(profile_page, namespace = 'profile-page')),
    url(r'^status/',include(update_status,namespace='status')),
    url(r'^statistic/', include(statistic,namespace='statistic')),
	url(r'^friend/', include(friend,namespace='friend')),
    url(r'^$', RedirectView.as_view(url='/status/',permanent='true'), name='index'),
]

statistic/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, update_status, delete_status

urlpatterns=[
    url(r'^$', index, name='index'),
    url(r'^update_status/', update_status,name='update_status'),
    url(r'^delete_status/',delete_status,name='delete_status'),
]

add_friend/models.py
from django.db import models

class Add_Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

profile_page/models.py
from django.db import models

# Create your models here.

statistic/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'class': 'friend-name',
        'placeholder':'Masukkan Nama'
    }
    description_attrs = {
        'type': 'url',
        'class': 'friend-url',
        'placeholder':'Masukkan url'
    }

    name = forms.CharField(label='', required=True, max_length=32, widget=forms.TextInput(attrs=title_attrs))
    url = forms.URLField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    attrs = {
        'type': 'text',
        'class': 'status_form',
        'placeholder':'What are you thinking today?',
    }
    status = forms.CharField(label='', required=True, max_length=140, widget=forms.Textarea(attrs=attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend_Form
from .models import Add_Friend

response = {}
# Create your views here.
def index(request):
	response['form'] = Add_Friend_Form
	fren = Add_Friend.objects.all()
	response['fren'] = fren
	html = 'add_friend/add_friend.html'
	response['add_friend_form'] = Add_Friend_Form
	return render(request, html, response)
	
def add_friend(request):
	form = Add_Friend_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
		response['url'] = request.POST['url'] if request.POST['url'] != "" else "Anonymous"
		message = Add_Friend(name=response['name'], url=response['url'])
		message.save()
		return HttpResponseRedirect('/friend/')
	else:
		return HttpResponseRedirect('/friend/')
		

profile_page/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
response = {'author': "Hepzibah Sith"} #TODO Implement yourname
birthday = '13 Jan 1057'
gender =  'Male'
expertise = 'Marketing Collector Public Speaking'
description = 'Antique expert, Experience as marketer for 10 years'
email = 'hello@sith.com'

def index(request):
	html = 'profile_page/profile_page.html'
	response['birthday'] = birthday
	response['gender'] = gender
	response['expertise'] = expertise
	response['description'] = description
	response['email'] = email
	return render(request, html, response)

statistic/views.py
from django.shortcuts import render
from update_status.models import Status
from add_friend.models import Add_Friend
import profile_page.views as profile

response = {}

def index(request):
    response['name'] = profile.response['author']
    response['birthday'] = profile.birthday
    response['email'] = profile.email
    response['friends'] = Add_Friend.objects.count()
    response['feeds'] = Status.objects.count()
    if Status.objects.count() > 0:
        response['last_feed'] = list(Status.objects.all())[Status.objects.count()-1]
    else:
        response['last_feed'] = "No Posts Yet!"
    html = 'statistic/statistic.html'
    return render(request, html, response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from profile_page.views import response as resp
from .forms import Status_Form
from .models import Status

# Create your views here.

response = {}
def index(request):
    response['status_form'] = Status_Form
    response['status'] = Status.objects.all()[::-1]
    response['name'] = resp['author']
    html = 'update_status/status.html'
    return render(request,html,response)

def update_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        status = request.POST['status']
        status = Status(status = status)
        status.save()
    return HttpResponseRedirect('/status/')

def delete_status(request):
    if(request.method == 'POST'):
        id = int(request.POST['id'])
        Status.objects.filter(id=id).delete()
    return HttpResponse(' ')

add_friend/templates/add_friend/add_friend.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
{% endblock %}


{% block content %}
<div id="page_title"><b><i>Add Friend</i></b></div>
<hr/>
<section name="form">
	<div class="container">
		<form id="form" method="POST" action="{% url 'friend:add_friend' %}">
			<h2>Friend Form</h2>
			{% csrf_token %}
			{{ add_friend_form }}
			<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
			<br>
		</form>
	</div>

</section>
<br>
<br>

<section name="my-list" id="my-list">
	<div class="container">
		<h2 class="my-list-title">List Friend</h2>
		<div class="flex">
			{% if fren %}
				{% for data in fren %}
					<div class="flex-item">
						<div class="to-do-list">
							<div class="fren-name">
								{{data.name}}
							</div>
							<div class="to-do-list-url">
								<a href=http://{{data.url}}>{{data.url}}</a>
							</div>
							<div class="to-do-list-date-added">
								{{data.created_date}}
							</div>
						</div>
					</div>
				{% endfor %}
			{% else %}
			<div class="alert alert-danger text-center">
				<strong>Oops!</strong> Tidak ada data Todo.
			</div>
			{% endif %}
		</div>
	</div>
</section>



{% endblock %}

profile_page/templates/profile_page/profile_page.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile_page.css' %}" />
{% endblock %}

{% block content %}
<div id="page_title"><b><i>Profile Page</i></b></div>
<hr/>
<div name = "profile" id = "name" align = "center">
    <p>
        <img src="{% static 'img/profil.jpg' %}" alt="Hepzibah Smith" width="150" height="150" style="border-radius: 50% ">
        <h1>
            {{author}}
        </h1>
    </p>

</div>

<div id = "bio">
    <div name="birthday" align = "center">

        <h4>Birthday    : {{birthday}}</h4>

    </div>

    <div name="gender" align = "center">

       <h4>Gender      : {{gender}}</h4>

    </div>

    <div name="expertise" align = "center">

        <h4>Expertise   : {{expertise}}</h4>

    </div>

    <div name="description" align = "center">

        <h4>Description : {{description}}</h4>

    </div>

    <div name="email" align = "center">

        <h4>Email       : {{email}}</h4>

    </div>
</div>

{% endblock %}

statistic/templates/statistic/statistic.html
{% extends "layout/base.html" %}
{% load staticfiles %}


{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" />
{% endblock %}


{% block content %}
<div id="page_title"><b><i>Statistic</i></b></div>
<hr/>
<div class="center_screen">
    <div id = "sameline1">
        <img src="{% static 'img/profil.jpg' %}" alt="Hepzibah Smith" width="180" height="180" style="border-radius: 50%">
    </div>
    <div id = "sameline2">
        <a href="{% url 'profile-page:index' %}">{{name}}</a>
        <div id = "birthdate"><i>Born on {{birthday}}</i></div>
        <div id = "email">{{email}}</div>
    </div>
    <br>
    <div id = "sameline3">
        <a href="{% url 'friend:index' %}">Friends</a>
        <p><b>{{friends}}</b> People</p>
    </div>
    <div id = "sameline4">
        <a href="{% url 'status:index' %}">Feeds</a>
        <p><b>{{feeds}}</b> Post</p>
    </div>

    <h3>Latest Post</h3>
    <div id = mini_prof_pic>
        <img src=https://i0.wp.com/instageeked.com/wp-content/uploads/2015/10/tumblr_m4bx9cUI7t1qbwnuho1_1280.jpg alt="Hepzibah Smith" width="50" height="50" style="border-radius: 50%">
    </div>
    <div id = "last_feed">
        "{{last_feed.status}}"
    </div>
    <div id = "last_feed_timestamp"><i>on {{last_feed.created_date}}</i></div>


</div>

{% endblock %}

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Social Media">
  <meta name="author" content="Benny Ghalsa Miki Tirta">
  <!-- bootstrap css -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <!-- Font Family -->
  <link href="https://fonts.googleapis.com/css?family=Bungee+Shade" rel="stylesheet">
  {% block static %}
  <!-- stylesheet goes here-->
  {% endblock %}
  <title>
    {% block title %} Welcome to Socmed {% endblock %}
  </title>
</head>

<body>
  <header>
    {% include "partials/header.html" %}
  </header>
  <br>
  <br>
  <content>
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
  </content>
  <footer>
    {% include "partials/footer.html" %}
  </footer>

  <!-- Jquery n Bootstrap Script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
    $(document).ready(function() {
      // get current URL path and assign 'active' class
      var pathname = window.location.pathname;
      $('.nav > li > a[href="' + pathname + '"]').parent().addClass('active');
    })
  </script>
  {% block script %}
  <!-- script goes here -->
  {% endblock %}
</body>

</html>

templates/partials/footer.html
<p> &copy; Benny Miki Ghalsa Tirta</p>

templates/partials/header.html
{% load staticfiles %}
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <a class="brand" href="{% url 'index' %}"><!--img src="{% static 'img/logo.png' %}" alt="SocMed"--> SOCMED
        </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'status:index' %}"> Status </a></li>
        <li><a href="{% url 'profile-page:index' %}"> Profile </a> </li>
        <li><a href="{% url 'friend:index' %}"> Friends </a></li>
        <li><a href="{% url 'statistic:index' %}"> Stats </a></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
  <!--/.container-fluid -->
</nav>

update_status/templates/update_status/status.html
{% extends "layout/base.html" %} {% load staticfiles %} {% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
{% endblock %}

{% block script %}
<script>
$(".delete-button").on("click",function(){
	var id = $(this).data('id');
	$.ajax({
		url:"delete_status",
		type:"POST",
		data:{csrfmiddlewaretoken:document.getElementsByName('csrfmiddlewaretoken')[0].value, "id":id},
		dataType: "json",
	});
	location.href="/status/";
});
</script>
{% endblock %}

{% block content %}
<div id="page_title"><b><i>Update Status</i></b></div>
<hr/>
<section>
<form id="form" method="POST" action="{% url 'status:update_status' %}" }>
	{% csrf_token %}
	{{ status_form }}
	<br/>
	<input class="btn btn-lg	 btn-primary btn-info" id="submit" type="submit" value="Post">
</form>
</section>
<section>
<ul class="timeline">
	{% if status %}
  {% for data in status %}
	<li>
		<div class="avatar">
				<img src="{% static 'img/profil.jpg' %}">
					<div class="hover">
					<a href="{% url 'profile-page:index'%}">Click</a>
				</div>
		</div>
		<div class="bubble-container">
			<div class="bubble">
				<h3>{{name}}</h3><br/>
				{{data.status}}
				<div class="date">{{data.created_date}}</div>
				<div class="over-bubble">
					<div class="delete-button">Delete</div>
				</div>
			</div>

		</div>
	</li>
  {% endfor %}
</ul>
  {% else %}
    <div class="alert alert-danger text-center">
        <strong>Sorry!</strong> You haven't updated your status.
    </div>
  {% endif %}
</section>

{% endblock %}